# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

fib = 0
birinci = 0
ikinci = 1
toplam = 0

while fib < 4000000:
    fib = birinci + ikinci
    birinci = ikinci
    ikinci = fib
    if fib % 2 == 0:
        toplam += fib

print("Sonuç: ",toplam)



"""
0
1
1
2
3
5
8


"""
